In [5]:
import pandas as pd
messages=pd.read_csv(r'C:\Users\Rashu\Downloads\NLP\SMSSpamCollection.txt',sep='\t',names=["label",'message'])
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [6]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rashu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [8]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=" ".join(review)
  corpus.append(review)

In [9]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

### Create Bag Of Words

In [13]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values
y

array([ True,  True, False, ...,  True,  True,  True])

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))


In [16]:
len(X_train),len(y_train)

(4457, 4457)

In [17]:
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [18]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [19]:
cv.vocabulary_


{'yet': 2490,
 'like': 1168,
 'keep': 1075,
 'touch': 2166,
 'way': 2353,
 'ru': 1775,
 'hous': 978,
 'keep touch': 1080,
 'ill': 1004,
 'littl': 1184,
 'bu': 227,
 'stop': 1984,
 'street': 1999,
 'bu stop': 228,
 'might': 1316,
 'coupl': 452,
 'buck': 229,
 'send': 1831,
 'tomorrow': 2151,
 'love': 1224,
 'ya': 2470,
 'love ya': 1232,
 'back': 134,
 'lemm': 1149,
 'know': 1095,
 'readi': 1700,
 'lemm know': 1150,
 'hope': 966,
 'kind': 1090,
 'day': 498,
 'one': 1495,
 'load': 1188,
 'reason': 1706,
 'smile': 1907,
 'urgent': 2269,
 'week': 2367,
 'free': 730,
 'prize': 1651,
 'txt': 2201,
 'word': 2432,
 'claim': 359,
 'www': 2453,
 'net': 1419,
 'pobox': 1606,
 'week free': 2370,
 'txt word': 2211,
 'say': 1797,
 'hi': 936,
 'get': 781,
 'ass': 105,
 'south': 1940,
 'tampa': 2049,
 'prefer': 1637,
 'say hi': 1799,
 'south tampa': 1941,
 'go': 806,
 'take': 2042,
 'bath': 147,
 'place': 1588,
 'key': 1083,
 'window': 2407,
 'go take': 822,
 'song': 1926,
 'aiyo': 44,
 'poor': 1616,
 

In [20]:
from sklearn.naive_bayes import MultinomialNB


In [21]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)


In [22]:
y_pred=spam_detect_model.predict(X_test)


In [23]:
from sklearn.metrics import accuracy_score,classification_report


In [24]:
accuracy_score(y_test,y_pred)


0.989237668161435

In [26]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

       False       0.97      0.95      0.96       153
        True       0.99      1.00      0.99       962

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



### Creating The TF-IDF Model

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [29]:
X_train


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0.332, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 

In [30]:
tv.vocabulary_


{'look': 1196,
 'forward': 714,
 'sex': 1841,
 'cuddl': 453,
 'two': 2192,
 'sleep': 1888,
 'look forward': 1197,
 'sorri': 1928,
 'left': 1139,
 'phone': 1552,
 'ok': 1471,
 'might': 1300,
 'would': 2438,
 'bird': 169,
 'one': 1486,
 'date': 481,
 'wake': 2314,
 'sinc': 1871,
 'check': 321,
 'stuff': 2000,
 'saw': 1790,
 'true': 2179,
 'avail': 114,
 'space': 1938,
 'pl': 1568,
 'call': 236,
 'send': 1820,
 'mail': 1242,
 'pl call': 1569,
 'shall': 1845,
 'book': 191,
 'half': 896,
 'know': 1092,
 'account': 8,
 'detail': 518,
 'ask': 100,
 'mom': 1344,
 'reach': 1688,
 'cheer': 322,
 'babe': 128,
 'later': 1116,
 'chat': 319,
 'lol': 1190,
 'real': 1694,
 'told': 2146,
 'dad': 471,
 'cancer': 278,
 'noe': 1430,
 'busi': 226,
 'realli': 1697,
 'bore': 192,
 'msg': 1369,
 'oso': 1508,
 'dunno': 573,
 'wat': 2334,
 'colour': 368,
 'choos': 330,
 'arm': 90,
 'fine': 687,
 'uni': 2221,
 'hey': 925,
 'angri': 63,
 'repli': 1725,
 'chanc': 308,
 'soon': 1925,
 'number': 1454,
 'cool': 421,


In [31]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [32]:
y_pred=spam_tfidf_model.predict(X_test)


In [33]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9766816143497757


In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.83      0.96      0.89       114
        True       1.00      0.98      0.99      1001

    accuracy                           0.98      1115
   macro avg       0.91      0.97      0.94      1115
weighted avg       0.98      0.98      0.98      1115

